import type { ApprovedBrief } from "./discovery.ts";
import type { IssueSnapshot, Question } from "./workflow-contracts.ts";

export const TRIAGE_DISCLAIMER = "> *This was generated by AI during triage.*";
export const TRIAGE_STATES = [
  "needs-triage",
  "needs-info",
  "ready-for-agent",
  "ready-for-human",
  "wontfix",
] as const;
export interface TriageContext {
  title: string;
  author: string;
  createdAt: string;
  updatedAt: string;
  contentRevision: string;
  childIds?: string[];
  comments: {
    id: number;
    author: string;
    body: string;
    createdAt: string;
    updatedAt: string;
    url: string;
  }[];
}
export interface TriageProposal {
  category: "bug" | "enhancement";
  state: (typeof TRIAGE_STATES)[number];
  investigation: string;
  recommendation: string;
  verification: string;
  comment: string;
  wontfixReason?: "already-implemented" | "rejected";
  /** A rejected enhancement records the original skill's knowledge document in a draft PR. */
  knowledge?: { path: string; content: string };
  documents?: { path: string; content: string }[];
}
export interface TriageReceipt {
  commentRef: string;
  knowledgeRef?: string;
  approvedBrief?: ApprovedBrief;
}
export interface TriageRequest {
  operationId: string;
  runId: string;
  issue: IssueSnapshot;
  proposal: TriageProposal;
}
export interface TriageAdapter {
  /** Native writers recheck the coordinator gate immediately before each external mutation. */
  configureActionGuard?(guard: (runId: string) => void): void;
  prepare(issue: IssueSnapshot): Promise<IssueSnapshot>;
  current?(issue: IssueSnapshot): Promise<boolean>;
  apply(request: TriageRequest): Promise<TriageReceipt>;
  reconcile(request: TriageRequest): Promise<TriageReceipt | undefined>;
  approvedBriefs?(): Promise<ApprovedBrief[]>;
}
export function validateTriageProposal(proposal: TriageProposal) {
  if (
    !proposal ||
    !["bug", "enhancement"].includes(proposal.category) ||
    !TRIAGE_STATES.includes(proposal.state) ||
    [proposal.investigation, proposal.recommendation, proposal.verification, proposal.comment].some(
      (value) => typeof value !== "string" || !value.trim(),
    ) ||
    !proposal.comment.startsWith(`${TRIAGE_DISCLAIMER}\n`)
  )
    throw new Error(
      "Triage proposal requires investigation, recommendation, verification and disclaimer",
    );
  if (
    proposal.state === "wontfix" &&
    !["already-implemented", "rejected"].includes(proposal.wontfixReason ?? "")
  )
    throw new Error("Wontfix requires an explicit reason");
  const needsKnowledge =
    proposal.state === "wontfix" &&
    proposal.category === "enhancement" &&
    proposal.wontfixReason === "rejected";
  if (needsKnowledge !== Boolean(proposal.knowledge))
    throw new Error("Only rejected enhancements require a rejection knowledge document");
  if (
    proposal.knowledge &&
    (!/^\.out-of-scope\/[a-z0-9-]+\.md$/.test(proposal.knowledge.path) ||
      !proposal.knowledge.content.trim())
  )
    throw new Error("Invalid rejection knowledge document");
  if (
    proposal.documents?.some(
      (document) =>
        !/^(docs\/context\/root\.md|docs\/adr\/[0-9][a-z0-9.-]*\.md)$/.test(document.path) ||
        typeof document.content !== "string" ||
        !document.content.trim(),
    )
  )
    throw new Error("Triage documents must be the domain context or scoped ADRs");
  const paths = triageDocuments(proposal).map((document) => document.path);
  if (new Set(paths).size !== paths.length) throw new Error("Duplicate triage document paths");
}
export function triageDocuments(proposal: TriageProposal) {
  return [...(proposal.documents ?? []), ...(proposal.knowledge ? [proposal.knowledge] : [])];
}
export function triageApproval(proposal: TriageProposal): Question {
  validateTriageProposal(proposal);
  return {
    prompt: `Apply this triage outcome?\n\nCategory: ${proposal.category}\nState: ${proposal.state}\n\nInvestigation\n${proposal.investigation}\n\nRecommendation\n${proposal.recommendation}\n\nVerification\n${proposal.verification}\n\nExact comment\n${proposal.comment}${triageDocuments(
      proposal,
    )
      .map(
        (document) => `\n\nCreate draft documentation PR for ${document.path}\n${document.content}`,
      )
      .join("")}${proposal.state === "wontfix" ? "\n\nClose issue as not planned." : ""}`,
    options: [
      { id: "apply", label: "Apply outcome" },
      { id: "revise", label: "Revise outcome" },
    ],
    allowFreeform: true,
  };
}
