/** Deterministic external-provider fixture. Loaded only by the dedicated network-none test image. */
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import {
  type AssistantMessage,
  createAssistantMessageEventStream,
} from "@earendil-works/pi-ai/compat";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function fixture(pi: ExtensionAPI) {
  pi.registerProvider("openai-codex", {
    baseUrl: "http://fixture.invalid",
    apiKey: "credential-free-test",
    api: "factory-test-only",
    models: [
      {
        id: "gpt-6-astra",
        name: "Deterministic test fixture",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 1000,
      },
    ],
    streamSimple(model, context, options) {
      const request = JSON.parse(
        readFileSync(process.env.FACTORY_REQUEST ?? "/phase/request.json", "utf8"),
      );
      const axis = process.env.FACTORY_REVIEW_AXIS;
      const observations = "/state/provider-dispatched.jsonl";
      const previousCalls = existsSync(observations)
        ? readFileSync(observations, "utf8")
            .trim()
            .split("\n")
            .map((line) => JSON.parse(line))
            .filter((call) => call.owner === request.operationId && !call.summarizing).length
        : 0;
      const summarizing = context.systemPrompt?.startsWith(
        "You are a context summarization assistant",
      );
      const phaseMessages = request.integration
        ? context.messages.slice(
            context.messages.findLastIndex((message) => message.role === "user") + 1,
          )
        : context.messages;
      const results = phaseMessages.filter((message) => message.role === "toolResult");
      const names = results.map((message) =>
        message.role === "toolResult" ? message.toolName : "",
      );
      const lastUser = [...context.messages].reverse().find((message) => message.role === "user");
      appendFileSync(
        "/state/protocol-observations.jsonl",
        `${JSON.stringify({ uid: process.getuid?.(), axis, model: model.id, provider: model.provider, user: lastUser, session: process.env.FACTORY_MODEL_OWNER ?? request.session.id })}\n`,
      );
      let tool: { name: string; arguments: Record<string, unknown> };
      if (request.issue.route === "triage") {
        if (!names.includes("bash"))
          tool = {
            name: "bash",
            arguments: {
              command:
                "cat /resources/skills/triage/AGENT-BRIEF.md /resources/skills/triage/OUT-OF-SCOPE.md; git ls-files",
            },
          };
        else if (!request.answer)
          tool = {
            name: "request_user_input",
            arguments: {
              prompt:
                "Searched components and prior rejection records. Recommend enhancement / ready-for-agent. Verify the claim?",
              allowFreeform: true,
            },
          };
        else if (!names.includes("factory_triage_propose"))
          tool = {
            name: "factory_triage_propose",
            arguments: {
              category: "enhancement",
              state: "ready-for-agent",
              investigation:
                "Searched tracked source and prior rejection records; no greeting exists.",
              recommendation: "A small well specified agent task.",
              verification: "Confirmed missing greeting component.",
              comment:
                "> *This was generated by AI during triage.*\n\n## Agent brief\nCreate greeting.\n\n## Acceptance criteria\nRender the agreed greeting.",
            },
          };
        else tool = { name: "factory_failed", arguments: { reason: "Triage proposal rejected" } };
      } else if (axis)
        tool = {
          name: "review_result",
          arguments: {
            passed: request.issue.number !== 2,
            findings: request.issue.number === 2 ? ["Fixture review failure"] : [],
          },
        };
      else if (request.issue.number === 10)
        tool = {
          name: "factory_no_change",
          arguments: { reason: "Requested behavior already exists" },
        };
      else if (request.issue.number === 3)
        tool = { name: "Skill", arguments: { name: "uncaptured-dependency" } };
      else if (request.issue.number === 4)
        tool = process.env.FACTORY_DELEGATE_RESULT
          ? { name: "bash", arguments: { command: "sleep 120" } }
          : { name: "spawn_agent", arguments: { task: "Run cancellation probe" } };
      else if (request.issue.number === 7 && !request.answer && previousCalls < 3)
        tool = { name: "read", arguments: { path: "/resources/skills/fixture/large.txt" } };
      else if (!request.answer)
        tool = {
          name: "request_user_input",
          arguments: { prompt: "Choose fixture implementation", allowFreeform: true },
        };
      else if (request.integration && !names.includes("bash"))
        tool = {
          name: "bash",
          arguments: {
            command:
              "test -f .git/MERGE_HEAD && test -n \"$(git ls-files -u)\" && printf 'child and sibling\\n' > result.txt",
          },
        };
      else if (!names.includes("bash"))
        tool = {
          name: "bash",
          arguments: { command: "cat /resources/skills/fixture/support.txt > result.txt" },
        };
      else if (!names.includes("checkpoint_commit"))
        tool = { name: "checkpoint_commit", arguments: {} };
      else if (!names.includes("factory_validate"))
        tool = { name: "factory_validate", arguments: {} };
      else if (request.integration && !names.includes("Skill"))
        tool = { name: "Skill", arguments: { name: "code-review" } };
      else if (names.filter((name) => name === "spawn_agent").length === 0)
        tool = {
          name: "spawn_agent",
          arguments: { task: "Independently review standards", axis: "standards" },
        };
      else if (names.filter((name) => name === "spawn_agent").length === 1)
        tool = {
          name: "spawn_agent",
          arguments: { task: "Independently review specification", axis: "spec" },
        };
      else if (request.issue.number === 6 && names.filter((name) => name === "bash").length === 1)
        tool = { name: "bash", arguments: { command: "echo dirty >> result.txt" } };
      else if (!names.includes("factory_complete"))
        tool = { name: "factory_complete", arguments: {} };
      else
        tool = {
          name: "factory_failed",
          arguments: { reason: "Fixture completion rejected unsuccessful evidence" },
        };
      const stream = createAssistantMessageEventStream();
      const message: AssistantMessage = {
        role: "assistant",
        content: [
          {
            type: "toolCall",
            id: `fixture-${context.messages.length}`,
            name: tool.name,
            arguments: tool.arguments,
          },
        ],
        api: model.api,
        provider: model.provider,
        model: model.id,
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
        },
        stopReason: "toolUse",
        timestamp: Date.now(),
      };
      if (summarizing) {
        message.content = [
          {
            type: "text",
            text: "Preserve the fixture issue, captured resources and existing workspace. Continue from the saved human answer.",
          },
        ];
        message.stopReason = "stop";
      } else if (request.issue.number === 7 && request.phase === 0) {
        message.usage.input = 190000;
        message.usage.totalTokens = 190000;
      }
      setTimeout(
        async () => {
          await options?.onPayload?.({ fixture: true }, model);
          appendFileSync(
            "/state/provider-dispatched.jsonl",
            `${JSON.stringify({
              owner: process.env.FACTORY_MODEL_OWNER ?? request.operationId,
              summarizing,
            })}\n`,
          );
          if ([8, 9].includes(request.issue.number)) {
            message.stopReason = "error";
            message.errorMessage =
              request.issue.number === 8 ? "usage_limit_reached" : "401 unauthorized";
            stream.push({ type: "error", reason: "error", error: message });
            stream.end();
            return;
          }
          if (results.length > 40) {
            message.stopReason = "error";
            message.errorMessage = "Fixture exceeded bounded protocol steps";
            stream.push({ type: "error", reason: "error", error: message });
            stream.end();
            return;
          }
          await new Promise((resolve) => setTimeout(resolve, request.permits ? 80 : 0));
          stream.push({ type: "start", partial: message });
          stream.push({ type: "done", reason: summarizing ? "stop" : "toolUse", message });
          stream.end();
        },
        request.permits ? 80 : 0,
      );
      return stream;
    },
  });
}
