// This file is generated by Velite

export { default as docs } from './docs.json' with { type: 'json' }
export { default as ui } from './ui.json' with { type: 'json' }
export { default as blocks } from './blocks.json' with { type: 'json' }
export { default as changelog } from './changelog.json' with { type: 'json' }