// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type docs = Collections['docs']['schema']['_output']
export declare const docs: docs[]

export type ui = Collections['ui']['schema']['_output']
export declare const ui: ui[]

export type blocks = Collections['blocks']['schema']['_output']
export declare const blocks: blocks[]

export type changelog = Collections['changelog']['schema']['_output']
export declare const changelog: changelog[]
