const DEFAULT_CROP_SIZE = 120;
const DEFAULT_CROP_RATIO = 0.72;
const DEFAULT_ASPECT_RATIO = 1;
const MAX_STAGE_WIDTH_RATIO = 0.92;
const MAX_STAGE_HEIGHT_RATIO = 0.9;

export {
  DEFAULT_ASPECT_RATIO,
  DEFAULT_CROP_RATIO,
  DEFAULT_CROP_SIZE,
  MAX_STAGE_HEIGHT_RATIO,
  MAX_STAGE_WIDTH_RATIO,
};
