/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/_website'
import { Route as WebsiteChar123SlugChar125RouteImport } from './routes/_website.{-$slug}'
import { Route as WebsiteInstallationSlugRouteImport } from './routes/_website.installation.$slug'
import { Route as PreviewRegistryPrimitiveSlugRouteImport } from './routes/preview.$registry.$primitive.$slug'
import { Route as WebsiteRegistryRegistryChar123SlugChar125RouteImport } from './routes/_website.registry.$registry.{-$slug}'
import { Route as WebsiteRegistryRegistrySlugDocsRouteImport } from './routes/_website.registry.$registry.$slug.docs'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteChar123SlugChar125Route =
  WebsiteChar123SlugChar125RouteImport.update({
    id: '/{-$slug}',
    path: '/{-$slug}',
    getParentRoute: () => WebsiteRoute,
  } as any)
const WebsiteInstallationSlugRoute = WebsiteInstallationSlugRouteImport.update({
  id: '/installation/$slug',
  path: '/installation/$slug',
  getParentRoute: () => WebsiteRoute,
} as any)
const PreviewRegistryPrimitiveSlugRoute =
  PreviewRegistryPrimitiveSlugRouteImport.update({
    id: '/preview/$registry/$primitive/$slug',
    path: '/preview/$registry/$primitive/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteRegistryRegistryChar123SlugChar125Route =
  WebsiteRegistryRegistryChar123SlugChar125RouteImport.update({
    id: '/registry/$registry/{-$slug}',
    path: '/registry/$registry/{-$slug}',
    getParentRoute: () => WebsiteRoute,
  } as any)
const WebsiteRegistryRegistrySlugDocsRoute =
  WebsiteRegistryRegistrySlugDocsRouteImport.update({
    id: '/registry/$registry/$slug/docs',
    path: '/registry/$registry/$slug/docs',
    getParentRoute: () => WebsiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebsiteRouteWithChildren
  '/{-$slug}': typeof WebsiteChar123SlugChar125Route
  '/installation/$slug': typeof WebsiteInstallationSlugRoute
  '/registry/$registry/{-$slug}': typeof WebsiteRegistryRegistryChar123SlugChar125Route
  '/preview/$registry/$primitive/$slug': typeof PreviewRegistryPrimitiveSlugRoute
  '/registry/$registry/$slug/docs': typeof WebsiteRegistryRegistrySlugDocsRoute
}
export interface FileRoutesByTo {
  '/': typeof WebsiteRouteWithChildren
  '/{-$slug}': typeof WebsiteChar123SlugChar125Route
  '/installation/$slug': typeof WebsiteInstallationSlugRoute
  '/registry/$registry/{-$slug}': typeof WebsiteRegistryRegistryChar123SlugChar125Route
  '/preview/$registry/$primitive/$slug': typeof PreviewRegistryPrimitiveSlugRoute
  '/registry/$registry/$slug/docs': typeof WebsiteRegistryRegistrySlugDocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_website': typeof WebsiteRouteWithChildren
  '/_website/{-$slug}': typeof WebsiteChar123SlugChar125Route
  '/_website/installation/$slug': typeof WebsiteInstallationSlugRoute
  '/_website/registry/$registry/{-$slug}': typeof WebsiteRegistryRegistryChar123SlugChar125Route
  '/preview/$registry/$primitive/$slug': typeof PreviewRegistryPrimitiveSlugRoute
  '/_website/registry/$registry/$slug/docs': typeof WebsiteRegistryRegistrySlugDocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$slug}'
    | '/installation/$slug'
    | '/registry/$registry/{-$slug}'
    | '/preview/$registry/$primitive/$slug'
    | '/registry/$registry/$slug/docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{-$slug}'
    | '/installation/$slug'
    | '/registry/$registry/{-$slug}'
    | '/preview/$registry/$primitive/$slug'
    | '/registry/$registry/$slug/docs'
  id:
    | '__root__'
    | '/_website'
    | '/_website/{-$slug}'
    | '/_website/installation/$slug'
    | '/_website/registry/$registry/{-$slug}'
    | '/preview/$registry/$primitive/$slug'
    | '/_website/registry/$registry/$slug/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebsiteRoute: typeof WebsiteRouteWithChildren
  PreviewRegistryPrimitiveSlugRoute: typeof PreviewRegistryPrimitiveSlugRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website/{-$slug}': {
      id: '/_website/{-$slug}'
      path: '/{-$slug}'
      fullPath: '/{-$slug}'
      preLoaderRoute: typeof WebsiteChar123SlugChar125RouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/installation/$slug': {
      id: '/_website/installation/$slug'
      path: '/installation/$slug'
      fullPath: '/installation/$slug'
      preLoaderRoute: typeof WebsiteInstallationSlugRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/preview/$registry/$primitive/$slug': {
      id: '/preview/$registry/$primitive/$slug'
      path: '/preview/$registry/$primitive/$slug'
      fullPath: '/preview/$registry/$primitive/$slug'
      preLoaderRoute: typeof PreviewRegistryPrimitiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website/registry/$registry/{-$slug}': {
      id: '/_website/registry/$registry/{-$slug}'
      path: '/registry/$registry/{-$slug}'
      fullPath: '/registry/$registry/{-$slug}'
      preLoaderRoute: typeof WebsiteRegistryRegistryChar123SlugChar125RouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/registry/$registry/$slug/docs': {
      id: '/_website/registry/$registry/$slug/docs'
      path: '/registry/$registry/$slug/docs'
      fullPath: '/registry/$registry/$slug/docs'
      preLoaderRoute: typeof WebsiteRegistryRegistrySlugDocsRouteImport
      parentRoute: typeof WebsiteRoute
    }
  }
}

interface WebsiteRouteChildren {
  WebsiteChar123SlugChar125Route: typeof WebsiteChar123SlugChar125Route
  WebsiteInstallationSlugRoute: typeof WebsiteInstallationSlugRoute
  WebsiteRegistryRegistryChar123SlugChar125Route: typeof WebsiteRegistryRegistryChar123SlugChar125Route
  WebsiteRegistryRegistrySlugDocsRoute: typeof WebsiteRegistryRegistrySlugDocsRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteChar123SlugChar125Route: WebsiteChar123SlugChar125Route,
  WebsiteInstallationSlugRoute: WebsiteInstallationSlugRoute,
  WebsiteRegistryRegistryChar123SlugChar125Route:
    WebsiteRegistryRegistryChar123SlugChar125Route,
  WebsiteRegistryRegistrySlugDocsRoute: WebsiteRegistryRegistrySlugDocsRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WebsiteRoute: WebsiteRouteWithChildren,
  PreviewRegistryPrimitiveSlugRoute: PreviewRegistryPrimitiveSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
