name: Quality Assurance

on:
  push:

jobs:
  static-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Biome Lint + Format
        run: bun run check

      - name: Cache dist
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            dist
            .velite
          key: ${{ runner.os }}-${{ hashFiles('vite.config.ts', 'velite.config.ts', 'src/**', 'public/**', 'bun.lockb') }}

      - name: Assuring build is working
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun run build

      - name: Assuring registry build is working
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun run r:build:kobalte

      - name: TypeScript Compiler
        run: bun run compile

      - name: Validate current commit (last commit)
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose
