name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  get-tag:
    if: (github.head_ref == 'knope/pre-release' && github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Get tag of latest draft release"
        run: echo "tag_name=$(gh release list --repo ${{ github.repository }} --json 'isDraft,tagName' --jq '.[] | select(.isDraft) | .tagName')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
        id: get-tag
    outputs:
      tag_name: ${{ steps.get-tag.outputs.tag_name }}

  release:
    needs: [get-tag]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache dist
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            dist
            .velite
          key: ${{ runner.os }}-${{ hashFiles('vite.config.ts', 'velite.config.ts', 'src/**', 'public/**', 'bun.lockb') }}

      - name: Build project
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun run build

      - name: Build registry
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun run r:build:kobalte

      - name: Create release
        run: |
          gh release edit ${{ needs.get-tag.outputs.tag_name }} --draft=false --latest

      - name: Create tag
        run: |
          git tag ${{ needs.get-tag.outputs.tag_name }}
          git push origin ${{ needs.get-tag.outputs.tag_name }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
